"""empty message

Revision ID: 4f91f8e6df1a
Revises: 
Create Date: 2019-12-10 23:36:26.910590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f91f8e6df1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('ctype', sa.String(length=64), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    timezones_table = op.create_table('timezones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('date_last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['timezone_id'], ['timezones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('server', sa.String(length=128), nullable=True),
    sa.Column('login', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('api_token', sa.String(length=172), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connector_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connector_type_id'], ['connector_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('synchronizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('date_started_from', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worklogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('synchronization_id', sa.Integer(), nullable=False),
    sa.Column('date_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_stopped', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_synchronized', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.String(length=32), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['synchronization_id'], ['synchronizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    import pytz

    op.bulk_insert(
        timezones_table,
        [{'name': tz} for tz in pytz.all_timezones]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worklogs')
    op.drop_table('synchronizations')
    op.drop_table('connectors')
    op.drop_table('users')
    op.drop_table('timezones')
    op.drop_table('connector_types')
    # ### end Alembic commands ###
