"""empty message

Revision ID: dcbaf4d652b6
Revises: ebc36833232f
Create Date: 2020-12-22 16:03:24.047695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcbaf4d652b6'
down_revision = 'ebc36833232f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worklogs', sa.Column('correct_id', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worklogs', 'correct_id')
    # ### end Alembic commands ###
