"""empty message

Revision ID: fe12aab5be25
Revises: ebc36833232f
Create Date: 2021-01-14 11:50:17.757044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe12aab5be25'
down_revision = 'ebc36833232f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connectors', sa.Column('_api_token', sa.String(length=255), nullable=True))
    op.add_column('connectors', sa.Column('_password', sa.String(length=255), nullable=True))
    op.drop_column('connectors', 'password')
    op.drop_column('connectors', 'api_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connectors', sa.Column('api_token', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('connectors', sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('connectors', '_password')
    op.drop_column('connectors', '_api_token')
    # ### end Alembic commands ###
